language: python
python:
  - "2.7"

sudo: false
cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=examples/adc_sample/adc_sample.ino
  - PLATFORMIO_CI_SRC=examples/read_buffer/read_buffer.ino
  - PLATFORMIO_CI_SRC=examples/sample_limit/sample_limit.ino

install:
  - pip install -U platformio
  - platformio update

script:
  - platformio ci --lib="."
    # atmelavr
    --board=micro
    --board=uno
    --board=due
    # atmelsam
    --board=tian
    --board=adafruit_feather_m0
    # espressif32
    --board=esp32dev
    --board=nodemcu-32s
    # espressif8266
    --board=esp12e
    # intel_arc32
    --board=genuino101
    # microchippic32
    --board=openbci
    # nordicnrf51
    --board=nrf51_dk
    # nordicnrf52
    --board=nrf52_dk
    # ststm32
    --board=genericSTM32F103C8
    --board=nucleo_f030r8
    # teensy
    --board=teensy20
    --board=teensy30
    --board=teensy31
    --board=teensy35
    --board=teensy36
    --board=teensylc
    # timsp430
    --board=lpmsp430f5529

#before_deploy:
#    - doxygen doc/Doxyfile
#    - touch doc/html/.nojekyll

#deploy:
#  provider: pages
#  github-token: $GITHUB_TOKEN
#  local_dir: doc/html
#  skip_cleanup: true
#  keep-history: true
#  on:
#      branch: master
