language: python
python:
  - "2.7"

sudo: false
cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=examples/adc_sample/adc_sample.ino
  - PLATFORMIO_CI_SRC=examples/read_buffer/read_buffer.ino
  - PLATFORMIO_CI_SRC=examples/sample_limit/sample_limit.ino

install:
  - pip install -U platformio
  - platformio update

script:
  - platformio ci --lib="."
    --board=uno
    --board=due
    --board=teensy31
    --board=esp12e

#before_deploy:
#    - doxygen doc/Doxyfile
#    - touch doc/html/.nojekyll

#deploy:
#  provider: pages
#  github-token: $GITHUB_TOKEN
#  local_dir: doc/html
#  skip_cleanup: true
#  keep-history: true
#  on:
#      branch: master
