language: python
python:
  - "2.7"

sudo: false
cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=examples/adc_sample/adc_sample.ino
  - PLATFORMIO_CI_SRC=examples/read_buffer/read_buffer.ino
  - PLATFORMIO_CI_SRC=examples/sample_limit/sample_limit.ino

install:
  - pip install -U platformio
  - platformio update

# atmelavr
# atmelsam
# espressif32
# espressif8266
# intel_arc32
# microchippic32
# nordicnrf51
# nordicnrf52
# ststm32
# teensy
# timsp430
script:
  - platformio ci --lib="."
    --board=micro
    --board=uno
    --board=due
    --board=tian
    --board=adafruit_feather_m0
    --board=esp32dev
    --board=nodemcu-32s
    --board=esp12e
    --board=genuino101
    --board=openbci
    --board=nrf51_dk
    --board=nrf52_dk
    --board=genericSTM32F103C8
    --board=nucleo_f030r8
    --board=teensy20
    --board=teensy30
    --board=teensylc
    --board=lpmsp430f5529

#before_deploy:
#    - doxygen doc/Doxyfile
#    - touch doc/html/.nojekyll

#deploy:
#  provider: pages
#  github-token: $GITHUB_TOKEN
#  local_dir: doc/html
#  skip_cleanup: true
#  keep-history: true
#  on:
#      branch: master
