language: python
python: "2.7"

sudo: false
cache:
  directories:
    - "~/.platformio"

jobs:
  include:
    ### stage: build
    - stage: build
      install:
        - pip install -U platformio
        - platformio update
      matrix:
        include:
          - name: "adc_sample.ino"
            env: PLATFORMIO_CI_SRC=examples/adc_sample/adc_sample.ino
          - name: "read_buffer.ino"
            env: PLATFORMIO_CI_SRC=examples/read_buffer/read_buffer.ino
          - name: "sample_limit.ino"
            env: PLATFORMIO_CI_SRC=examples/sample_limit/sample_limit.ino
        # atmelavr
        # atmelsam
        # espressif32
        # espressif8266
        # intel_arc32
        # nordicnrf51
        # nordicnrf52
        # ststm32
        # teensy
        script:
          - platformio ci --lib="."
            --board=micro
            --board=uno
            --board=due
            --board=tian
            --board=adafruit_feather_m0
            --board=esp32dev
            --board=nodemcu-32s
            --board=esp12e
            --board=genuino101
            --board=rfduino
            --board=nrf52_dk
            --board=genericSTM32F103CB
            --board=teensy20
            --board=teensy30
            --board=teensylc

    ### stage: deploy gh-pages
    - stage: GitHub gh-pages
      addons:
        apt:
          packages:
            - doxygen
            - doxygen-doc
      script: skip
      before_deploy:
        - doxygen doxygen.cfg
      deploy:
        provider: pages
        target-branch: gh-pages
        local_dir: docs/html
        skip-cleanup: true
        keep-history: true
        github-token: $GITHUB_TOKEN
        on:
          branch: master

    ### stage: deploy release
    - stage: GitHub release
      script: skip
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        skip_cleanup: true
        on:
          tags: true
